### ISSUE TITLE
Offline Play

### ISSUE THREAD

**Issue by SpicyRaymond** [cse442-spring-2020-offering/cse442-semester-project-bungalow-bois#3]
As a player, I want to play against a bot, so I can practice my skills before playing against other players.

**Comment by jameshess9** [comment]
1) Create a value function to rate board states
2) Implement an AI that picks the move with the highest value
3) Integrate AI into connect 4
4) Update UI to allow player to choose offline

**Comment by LingJackie** [comment]
Acceptance Test:
1) go to website
2) login/register using username and password
3) go to settings and click the play against bot option
4) play a full game of connect 4 with the bot
