### ISSUE TITLE
Accept/Deny Friend Requests

### ISSUE THREAD

**Issue by SpicyRaymond** [cse442-spring-2020-offering/cse442-semester-project-bungalow-bois#40]
As a player, I want to be able to accept or deny friend requests, so that I can pick and choose who I want to be my friend.

**Comment by SpicyRaymond** [comment]
Acceptance Test:
1) go to website
2) input username and password (register an account if needed)
3) click login button to login
4) See friend request from another player in the notification box
5) input their name into the the respond to friend request field 
6) click the accept or deny button
7) see that the notification is gone
8) if request was accepted: see the player in the friends list

**Comment by sultanol97** [comment]
You shouldnt be allowed to add the same friend more than once.
