### ISSUE TITLE
Undo Button

### ISSUE THREAD

**Issue by SpicyRaymond** [cse442-spring-2020-offering/cse442-semester-project-bungalow-bois#42]
As a gamer, I want to undo my last move, so I can fix my mistake of a move for local play.

**Comment by SpicyRaymond** [comment]
Acceptance test:
1) go to website
2) input username and password (register an account if needed)
3) click login button to login
5) play a game
6) see undo button

**Comment by sultanol97** [comment]
Undo button should keep the turn of the player.So if red player undo its still red players turn.
