### ISSUE TITLE
Create Undo Button

### ISSUE THREAD

**Issue by SpicyRaymond** [cse442-spring-2020-offering/cse442-semester-project-bungalow-bois#43]
Task test

- [ ] click any option(online, local, bot) on the game menu
- [ ] click start game button
- [ ] game board shows up
- [ ] click on any column on the board to make a move
- [ ] game piece appears on the bottom of the chosen column
- [ ] click undo button on the bottom of the board
- [ ] game piece disappears
- [ ] if game won undo button will not work

**Comment by Cackerman55** [comment]
These tests read more like an acceptance test. Please rewrite them to proper task test format.
