### ISSUE TITLE
Create Notification Box

### ISSUE THREAD

**Issue by LingJackie** [cse442-spring-2020-offering/cse442-semester-project-bungalow-bois#46]
Task Test

1. create notifications table in my php admin(stores 2 usernames)
2. have the friend request button went clicked store value into table 
3. have the invite to game button went clicked store value into table 
4. display values in table into a scroll box

**Comment by Cackerman55** [comment]
This is a great start to the task tests. What else needs to be added though?
Names? Times? Any kind of styling/css?
