### ISSUE TITLE
Friends List

### ISSUE THREAD

**Issue by SpicyRaymond** [cse442-spring-2020-offering/cse442-semester-project-bungalow-bois#5]
As a gamer, I want to see my friend(s), so I can see who I can play against.

**Comment by jameshess9** [comment]
1) Create SQL Table to store friends list
2) Integrate friends list into online connect 4 online play

**Comment by LingJackie** [comment]
Acceptance Test:
1) go to website
2) login or register using username and password
3)scroll down to see friends list on the main page
