### ISSUE TITLE
Set up the current game database

### ISSUE THREAD

**Issue by jameshess9** [cse442-spring-2020-offering/cse442-semester-project-bungalow-bois#50]
- [ ] Create a new table with the columns: Player1, Player2, turn, board state (2d array of ints) 
- [ ] Player 1 can not equal Player 2
- [ ] Board state can only contain 0 1 or 2
- [ ] Player1 and Player2 must both be registered users

**Comment by Cackerman55** [comment]
This is a good start. For the database this looks great.
