### ISSUE TITLE
View Other Players

### ISSUE THREAD

**Issue by SpicyRaymond** [cse442-spring-2020-offering/cse442-semester-project-bungalow-bois#7]
As a gamer, I want to see which players are online , so I can play against the person I choose.

**Comment by jameshess9** [comment]
1) Set up a server to host the connect 4 games
2) Create a front end application for each of the two players to use
3) Integrate connect 4 into backend application that hosts the games
4) Update UI to show online players

**Comment by LingJackie** [comment]
Acceptance Test:

1. go to website
2. input username and password (register an account if needed)
3. click login
4. see player list below the board
5. scroll through to find someone 
6. type their name into the challenge other players field 
7. click submit
