### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by LingJackie** [cse442-spring-2020-offering/cse442-semester-project-bungalow-bois#9]
As a player, I want to play with more pieces, like connect 5, so I can have more of a challenge.

**Comment by SupremeHackerMan** [comment]
Task:
1)Create a constructor for the board to take in board size
2)Have an option at the start of the game to choose connect 4, 5, 6,... etc

**Comment by LingJackie** [comment]
Acceptance test:
1) got to website
2) click on options
3) input size of board
4) play game 
5) see that board size is size specified
